serverAddr = "127.0.0.1"
serverPort = 8784
metadatas.token = "mys2ecret"

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
transport.useEncryption = true
