serverAddr = "127.0.0.1"
serverPort = 8784
metadatas.token = "mysecret"
transport.tls.certFile = "client.crt"
transport.tls.keyFile = "client.key"
transport.tls.trustedCaFile = "ca.crt"

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 24000
remotePort = 23000
transport.useEncryption = true
